### PR TITLE
Import zip

### PR DESCRIPTION
**Pull request by ToddLa**
zip file import
==========
mame4ios is registered as being able to open ZIP files.
so you can AirDrop a ZIP file to the app, or you can send one from Files.app or Dropbox.
or you can open a ZIP file from a email attachment.
a lot simpler than using iTunes or starting the server.

3 kinds of ZIP files are detected
romset, artwork, or a "zipset" (a ZIP of other ZIPs)

hardware keyboard
==============
if a hardware keyboard is attached (bluetooth, USB, or Xcode simulator) you can use it as a input device.  also has key bindings for a 8bitDo in keyboard mode.

Remove Gridlee
============

### CODE REVIEW

**Comment by mrjschulte** [comment]
checking it now.

**Comment by ToddLa** [comment]
Ok! I am ready for the final PR. I will pull merge and submit.

**Comment by mrjschulte** [comment]
I can't test my usb keyboard on the iPad Pro for some reason as it's not showing up as being connected... Suppose it'll be fine and we should merge this anyways.

**Comment by mrjschulte** [comment]
IT does look like the CRT and Scanlines are being applied to the entire "screen view" area now, and not the MAME Render buffer as I seem to recall was previously the case. The "frame" around the "screen view" extends above and below the active area that MAME is rendering into.

**Comment by mrjschulte** [comment]
Going back to a previous build from the 15th of February, it looks like at some point the relationship between the "screen view" area and the CRT/Scanlines filter area changed. Currently the "screen view" area appears to be scaled incorrectly.

**Comment by ToddLa** [comment]
Can you send screen shots showing the issues?

I toggled on/of the CRT and scan line filter and make sure they had the same text as the game View.

But maybe all the device combos something got lost.

Again the layout files were way out of date

On Feb 24, 2020, at 8:50 PM, MrJs <notifications@github.com> wrote:

﻿

Going back to a previous build from the 15th of February, it looks like at some point the relationship between the "screen view" area and the CRT/Scanlines filter area changed. Currently the "screen view" area appears to be scaled incorrectly.

**Comment by ToddLa** [comment]
There is some code that moves the frame based on safe area, maybe it does not adjust the overlay frame right

On Feb 24, 2020, at 8:50 PM, MrJs <notifications@github.com> wrote:

﻿

Going back to a previous build from the 15th of February, it looks like at some point the relationship between the "screen view" area and the CRT/Scanlines filter area changed. Currently the "screen view" area appears to be scaled incorrectly.

**Pull request merged**
