### PR TITLE
Modern ARC

### PR DESCRIPTION
**Pull request by ToddLa**
Update project to "modern" (recommended) settings.
including ARC! 🎉🥳🍾 and strict Xcode warnings.
removed 32bit target.
added README.md to the project to make it easy to edit.

### CODE REVIEW

**Comment by mrjschulte** [comment]
Looks great @ToddLa ! I'll wait for @yoshisuga to commit this and then I'll merge in the makefile to close out the last round of optimizations from my end.

**Comment by mrjschulte** [comment]
Looks like the frame around the image now has a vertical offset when enabling the "Scanline Effect" option when in Portrait mode.

**Comment by ToddLa** [comment]
I will turn on an overlay and look into it, is it minor shift/frame of obvious?

**Comment by ToddLa** [comment]
I see what you mean, the CRT frame is offset from the bottom, will bet money it is a safe area thing, easy fix.

**Comment by ToddLa** [comment]
The rect in the config/txt/skin files needed tweaked

Now that the simulator build works it is easier (but tedious) to go through all devices, landscape portrait fullscreen etc. (With crt effect on to see overlay frame)

What device are you seeing the overlay frame shift?

**Comment by ToddLa** [comment]
I am going through all the devices and fixing them, I will do a separate PR after the ARC changes go in.

**Comment by yoshisuga** [comment]
Awesome, thank you! Great work!! 🙏👍

**Pull request merged**
