### PR TITLE
RE-RELOADED MAME4iOS

### PR DESCRIPTION
**Pull request by ToddLa**
Sorry for the size of this pull request, I started out adding a UICollectionView based UI to choose a game and ended up updating to iOS 13 and Xcode 11, and making Siri Remote work on tvOS, ...

the app still works on at least iOS 10 (I tested that on a iPhone SE)

I left the code non-ARC

If you care, take a look at the README and my code, and let me know what you think....

Todd Laney
@ToddLa
ToddLa@HotMail.com

### CODE REVIEW

**Comment by yoshisuga** [comment]
Hi @ToddLa! Thanks for opening this PR! There's definitely a lot of stuff here, and great work on the UI! It really does make it feel like a first class iOS app, and it really enhances the experience of viewing content, and browsing content is way more enjoyable then scrolling through a list.

I'd definitely like to get the changes in, but I'm thinking we can create a new branch (native-ui?) and merge the PR to that one and continually improve the branch. I got an NSInternalInconsistencyException crash while filtering the collection view. The scroll performance is decent considering I have the full romset and I think we can make improvements to that as well - and exposing some of the filters, like favorites, maybe by using a `UITabBarController` .

Thanks so much for investing the time in this and taking the time to make a PR - this really ups the game a bit in terms of what's possible and I'd like to help with that as well. Let me know what you think!

**Comment by ToddLa** [comment]
Making a new native-ui branch sounds like a fine idea!

But some things should go into master, for example I got it to build without warnings or depreciations!

Also I switched to using UiAlertControler over UIAlertView and made GameConttollers able to interact with them.

Or maybe you want to leave all those changes in native-UI? After using it I can’t imagine anyone would want to go back to the DOSUI.

It would be very easy to have a setting “use new native UI” if that is an option you want to go...

Can you give me the details on the inconsistency assert? Just load full rom set and try to filter it?

I have two other branches going one that moves the whole project to ARC and another that adds a TopShelf to tvOS (showing Recent and Favorites)

I am also working on code to handle zip of zips, so you can copy (or Open in MAME4iOS) a single ROMS.zip

Does Load and Save state work on your builds? There is a timing problem in the myosd code when it tries to send two keys to MAME? I don’t *think* it is something I broke.  But I was gonna investigate.

Anyway let’s discuss how to proceed, this is a fun project to work on

Todd

On Feb 8, 2020, at 2:28 PM, yoshisuga <notifications@github.com> wrote:

﻿

Hi @ToddLa<https://github.com/ToddLa>! Thanks for opening this PR! There's definitely a lot of stuff here, and great work on the UI! It really does make it feel like a first class iOS app, and it really enhances the experience of viewing content, and browsing content is way more enjoyable then scrolling through a list.

I'd definitely like to get the changes in, but I'm thinking we can create a new branch (native-ui?) and merge the PR to that one and continually improve the branch. I got an NSInternalInconsistencyException crash while filtering the collection view. The scroll performance is decent considering I have the full romset and I think we can make improvements to that as well - and exposing some of the filters, like favorites, maybe by using a UITabBarController .

Thanks so much for investing the time in this and taking the time to make a PR - this really ups the game a bit in terms of what's possible and I'd like to help with that as well. Let me know what you think!

**Comment by ToddLa** [comment]
Also I assume jailbreak is not a config anymore?

What about 32-bit?

I made sure it works on iOS 10, any lower? Higher?

On Feb 8, 2020, at 2:28 PM, yoshisuga <notifications@github.com> wrote:

﻿

Hi @ToddLa<https://github.com/ToddLa>! Thanks for opening this PR! There's definitely a lot of stuff here, and great work on the UI! It really does make it feel like a first class iOS app, and it really enhances the experience of viewing content, and browsing content is way more enjoyable then scrolling through a list.

I'd definitely like to get the changes in, but I'm thinking we can create a new branch (native-ui?) and merge the PR to that one and continually improve the branch. I got an NSInternalInconsistencyException crash while filtering the collection view. The scroll performance is decent considering I have the full romset and I think we can make improvements to that as well - and exposing some of the filters, like favorites, maybe by using a UITabBarController .

Thanks so much for investing the time in this and taking the time to make a PR - this really ups the game a bit in terms of what's possible and I'd like to help with that as well. Let me know what you think!

**Comment by mrjschulte** [comment]
Great stuff @ToddLa! Super exciting to have someone join in and help take this project to the next level!

**Comment by yoshisuga** [comment]
Hi @ToddLa - again, great work on this, it's very encouraging to see the bold steps taken in your PR.

It'd be great if we can break out the changes (like resolving warnings, fixing deprecated calls like UIAlertView) into individual PRs so we can merge them in, but if that's too much work I'd say let's merge to a new branch and start making fixes on there.

I'll try to reproduce the inconsistency exception (sometimes hard to reproduce since it involves mutating the data source while the tableview is updating) and can help come up with a fix for that too.

I'm not putting any attention on supporting 32-bit devices, as I think the project should really focus on making MAME run for the latest iOS devices. That said, I think we can keep the 32-bit target around.

Thanks again, let me know what you think!

**Comment by ToddLa** [comment]
So what iOS version do you want to target? iOS 10? 11?
Anyone build it for older iOS versions?

-Todd

**Comment by yoshisuga** [comment]
Let's say minimum of iOS 10 for now. We should focus on 64-bit targets.

**Comment by mrjschulte** [comment]
The makefile refactoring I'm currently working on will also be a minimum of iOS 10 and be arm64 only.

**Comment by ToddLa** [comment]
great!

So how should I proceed? Do a branch with UiAleryView changes, and go forward like that?

**Comment by yoshisuga** [comment]
Yep! Create a new branch with the UIAlertController changes, and make a PR with master as the base.  Thanks!!!

**Comment by ToddLa** [comment]
Ok then we will go forward from there....

-Todd

On Feb 17, 2020, at 5:46 PM, yoshisuga <notifications@github.com> wrote:

﻿

Yep! Create a new branch with the UIAlertController changes, and make a PR with master as the base. Thanks!!!

**Pull request closed without merging**
