### PR TITLE
updated stvprot.c

### PR DESCRIPTION
**Pull request by Empier**
Fixed Tecmo World Cup '98 (player movement) issue.

### CODE REVIEW

**Comment by ToddLa** [comment]
Cool! Is this a fix specific to 139u1 or is it fixed in 230 mainline too?

**Comment by Empier** [comment]
p{margin-top:0;margin-bottom:0}
    


    - https://github.com/mamedev/mame/blob/master/src/mame/machine/315-5881_crypt.cppIn 230 it is solved in a different way.mame4ios use it in mame4ios without major changes.
==================

--------- 원본 메일 ---------

    
        보낸사람: Todd Laney ***@***.***>
        받는사람: yoshisuga/MAME4iOS ***@***.***>
        
            참조: KangMinsoo ***@***.***>, Author ***@***.***>
        
        날짜: 21.04.14 12:52 GMT +0900
        제목: Re: [yoshisuga/MAME4iOS] updated stvprot.c (#304)
        
        
    
    
        
Cool! Is this a fix specific to 139u1 or is it fixed in 230 mainline too?

**Comment by Empier** [comment]
This has already been resolved in the latest version.
 you can solved this problem without major changes.

**Comment by yoshisuga** [comment]
Thanks for the fix! It compiled so I'm assuming it works :)

**Pull request merged**
